{
 "title": "WAVEMQ",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Routed messages",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(route_published_messages[30s])",
     "legendFormat": "published messages per second"
    },
    {
     "expr": "rate(route_enqueued_messages[30s])",
     "legendFormat": "delivered messages per second"
    }
   ]
  },
  {
   "title": "Number of queues",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "queue_number", "legendFormat": "total queues" }
   ]
  },
  {
   "title": "Queue size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "queue_queued_bytes", "legendFormat": "total queue size" },
    { "expr": "queue_queued_messages", "legendFormat": "total queued messages" },
    { "expr": "queue_committed_messages", "legendFormat": "total on-disk messages" }
   ]
  },
  {
   "title": "Queue dropped messages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "queue_dropped_messages", "legendFormat": "dropped messages" },
    {
     "expr": "rate(queue_dropped_messages[30s])",
     "legendFormat": "drops per second"
    }
   ]
  },
  {
   "title": "Active Subscriptions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "route_active_subscriptions", "legendFormat": "active_subscriptions" }
   ]
  },
  {
   "title": "Denied operations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "peerserver_failed_publish", "legendFormat": "publish" },
    { "expr": "peerserver_failed_query", "legendFormat": "query" },
    { "expr": "peerserver_failed_subscribe", "legendFormat": "subscribe" }
   ]
  }
 ]
}