// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wavemq.proto

package pb

/*
Version 1.0
*/

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PeerSubscriptionTBS struct {
	SourceEntity         []byte   `protobuf:"bytes,1,opt,name=sourceEntity,proto3" json:"sourceEntity,omitempty"`
	Namespace            []byte   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Uri                  string   `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	Id                   string   `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerSubscriptionTBS) Reset()         { *m = PeerSubscriptionTBS{} }
func (m *PeerSubscriptionTBS) String() string { return proto.CompactTextString(m) }
func (*PeerSubscriptionTBS) ProtoMessage()    {}
func (*PeerSubscriptionTBS) Descriptor() ([]byte, []int) {
	return fileDescriptor_wavemq_4f4ebffe67269e9a, []int{0}
}
func (m *PeerSubscriptionTBS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerSubscriptionTBS.Unmarshal(m, b)
}
func (m *PeerSubscriptionTBS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerSubscriptionTBS.Marshal(b, m, deterministic)
}
func (dst *PeerSubscriptionTBS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerSubscriptionTBS.Merge(dst, src)
}
func (m *PeerSubscriptionTBS) XXX_Size() int {
	return xxx_messageInfo_PeerSubscriptionTBS.Size(m)
}
func (m *PeerSubscriptionTBS) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerSubscriptionTBS.DiscardUnknown(m)
}

var xxx_messageInfo_PeerSubscriptionTBS proto.InternalMessageInfo

func (m *PeerSubscriptionTBS) GetSourceEntity() []byte {
	if m != nil {
		return m.SourceEntity
	}
	return nil
}

func (m *PeerSubscriptionTBS) GetNamespace() []byte {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *PeerSubscriptionTBS) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *PeerSubscriptionTBS) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type PeerSubscription struct {
	Tbs                  *PeerSubscriptionTBS `protobuf:"bytes,1,opt,name=tbs,proto3" json:"tbs,omitempty"`
	Signature            []byte               `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	ProofDER             []byte               `protobuf:"bytes,3,opt,name=proofDER,proto3" json:"proofDER,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PeerSubscription) Reset()         { *m = PeerSubscription{} }
func (m *PeerSubscription) String() string { return proto.CompactTextString(m) }
func (*PeerSubscription) ProtoMessage()    {}
func (*PeerSubscription) Descriptor() ([]byte, []int) {
	return fileDescriptor_wavemq_4f4ebffe67269e9a, []int{1}
}
func (m *PeerSubscription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerSubscription.Unmarshal(m, b)
}
func (m *PeerSubscription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerSubscription.Marshal(b, m, deterministic)
}
func (dst *PeerSubscription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerSubscription.Merge(dst, src)
}
func (m *PeerSubscription) XXX_Size() int {
	return xxx_messageInfo_PeerSubscription.Size(m)
}
func (m *PeerSubscription) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerSubscription.DiscardUnknown(m)
}

var xxx_messageInfo_PeerSubscription proto.InternalMessageInfo

func (m *PeerSubscription) GetTbs() *PeerSubscriptionTBS {
	if m != nil {
		return m.Tbs
	}
	return nil
}

func (m *PeerSubscription) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *PeerSubscription) GetProofDER() []byte {
	if m != nil {
		return m.ProofDER
	}
	return nil
}

type PublishParams struct {
	Perspective *Perspective     `protobuf:"bytes,1,opt,name=perspective,proto3" json:"perspective,omitempty"`
	Namespace   []byte           `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Uri         string           `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	Content     []*PayloadObject `protobuf:"bytes,4,rep,name=content,proto3" json:"content,omitempty"`
	// If specified, the message will be encrypted
	EncryptionPartition [][]byte `protobuf:"bytes,5,rep,name=encryptionPartition,proto3" json:"encryptionPartition,omitempty"`
	// Should this message be persisted
	Persist bool `protobuf:"varint,6,opt,name=persist,proto3" json:"persist,omitempty"`
	// If specified, this proof will be used instead of building one
	CustomProofDER       []byte   `protobuf:"bytes,7,opt,name=customProofDER,proto3" json:"customProofDER,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishParams) Reset()         { *m = PublishParams{} }
func (m *PublishParams) String() string { return proto.CompactTextString(m) }
func (*PublishParams) ProtoMessage()    {}
func (*PublishParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_wavemq_4f4ebffe67269e9a, []int{2}
}
func (m *PublishParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishParams.Unmarshal(m, b)
}
func (m *PublishParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishParams.Marshal(b, m, deterministic)
}
func (dst *PublishParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishParams.Merge(dst, src)
}
func (m *PublishParams) XXX_Size() int {
	return xxx_messageInfo_PublishParams.Size(m)
}
func (m *PublishParams) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishParams.DiscardUnknown(m)
}

var xxx_messageInfo_PublishParams proto.InternalMessageInfo

func (m *PublishParams) GetPerspective() *Perspective {
	if m != nil {
		return m.Perspective
	}
	return nil
}

func (m *PublishParams) GetNamespace() []byte {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *PublishParams) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *PublishParams) GetContent() []*PayloadObject {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *PublishParams) GetEncryptionPartition() [][]byte {
	if m != nil {
		return m.EncryptionPartition
	}
	return nil
}

func (m *PublishParams) GetPersist() bool {
	if m != nil {
		return m.Persist
	}
	return false
}

func (m *PublishParams) GetCustomProofDER() []byte {
	if m != nil {
		return m.CustomProofDER
	}
	return nil
}

type PublishResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishResponse) Reset()         { *m = PublishResponse{} }
func (m *PublishResponse) String() string { return proto.CompactTextString(m) }
func (*PublishResponse) ProtoMessage()    {}
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_wavemq_4f4ebffe67269e9a, []int{3}
}
func (m *PublishResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishResponse.Unmarshal(m, b)
}
func (m *PublishResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishResponse.Marshal(b, m, deterministic)
}
func (dst *PublishResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishResponse.Merge(dst, src)
}
func (m *PublishResponse) XXX_Size() int {
	return xxx_messageInfo_PublishResponse.Size(m)
}
func (m *PublishResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PublishResponse proto.InternalMessageInfo

func (m *PublishResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type MessageTBS struct {
	SourceEntity         []byte           `protobuf:"bytes,1,opt,name=sourceEntity,proto3" json:"sourceEntity,omitempty"`
	SourceLocation       *LocationURI     `protobuf:"bytes,2,opt,name=sourceLocation,proto3" json:"sourceLocation,omitempty"`
	Namespace            []byte           `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Uri                  string           `protobuf:"bytes,4,opt,name=uri,proto3" json:"uri,omitempty"`
	Payload              []*PayloadObject `protobuf:"bytes,5,rep,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *MessageTBS) Reset()         { *m = MessageTBS{} }
func (m *MessageTBS) String() string { return proto.CompactTextString(m) }
func (*MessageTBS) ProtoMessage()    {}
func (*MessageTBS) Descriptor() ([]byte, []int) {
	return fileDescriptor_wavemq_4f4ebffe67269e9a, []int{4}
}
func (m *MessageTBS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageTBS.Unmarshal(m, b)
}
func (m *MessageTBS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageTBS.Marshal(b, m, deterministic)
}
func (dst *MessageTBS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageTBS.Merge(dst, src)
}
func (m *MessageTBS) XXX_Size() int {
	return xxx_messageInfo_MessageTBS.Size(m)
}
func (m *MessageTBS) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageTBS.DiscardUnknown(m)
}

var xxx_messageInfo_MessageTBS proto.InternalMessageInfo

func (m *MessageTBS) GetSourceEntity() []byte {
	if m != nil {
		return m.SourceEntity
	}
	return nil
}

func (m *MessageTBS) GetSourceLocation() *LocationURI {
	if m != nil {
		return m.SourceLocation
	}
	return nil
}

func (m *MessageTBS) GetNamespace() []byte {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *MessageTBS) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *MessageTBS) GetPayload() []*PayloadObject {
	if m != nil {
		return m.Payload
	}
	return nil
}

type Message struct {
	Proof                *Proof      `protobuf:"bytes,1,opt,name=proof,proto3" json:"proof,omitempty"`
	ProofDER             []byte      `protobuf:"bytes,2,opt,name=proofDER,proto3" json:"proofDER,omitempty"`
	Tbs                  *MessageTBS `protobuf:"bytes,3,opt,name=tbs,proto3" json:"tbs,omitempty"`
	Signature            []byte      `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	EncryptionPartition  [][]byte    `protobuf:"bytes,5,rep,name=encryptionPartition,proto3" json:"encryptionPartition,omitempty"`
	Timestamps           []int64     `protobuf:"varint,6,rep,packed,name=timestamps,proto3" json:"timestamps,omitempty"`
	Drops                []int64     `protobuf:"varint,7,rep,packed,name=drops,proto3" json:"drops,omitempty"`
	Persist              bool        `protobuf:"varint,8,opt,name=persist,proto3" json:"persist,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_wavemq_4f4ebffe67269e9a, []int{5}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetProof() *Proof {
	if m != nil {
		return m.Proof
	}
	return nil
}

func (m *Message) GetProofDER() []byte {
	if m != nil {
		return m.ProofDER
	}
	return nil
}

func (m *Message) GetTbs() *MessageTBS {
	if m != nil {
		return m.Tbs
	}
	return nil
}

func (m *Message) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Message) GetEncryptionPartition() [][]byte {
	if m != nil {
		return m.EncryptionPartition
	}
	return nil
}

func (m *Message) GetTimestamps() []int64 {
	if m != nil {
		return m.Timestamps
	}
	return nil
}

func (m *Message) GetDrops() []int64 {
	if m != nil {
		return m.Drops
	}
	return nil
}

func (m *Message) GetPersist() bool {
	if m != nil {
		return m.Persist
	}
	return false
}

type PayloadObject struct {
	Schema               string   `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayloadObject) Reset()         { *m = PayloadObject{} }
func (m *PayloadObject) String() string { return proto.CompactTextString(m) }
func (*PayloadObject) ProtoMessage()    {}
func (*PayloadObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_wavemq_4f4ebffe67269e9a, []int{6}
}
func (m *PayloadObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayloadObject.Unmarshal(m, b)
}
func (m *PayloadObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayloadObject.Marshal(b, m, deterministic)
}
func (dst *PayloadObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayloadObject.Merge(dst, src)
}
func (m *PayloadObject) XXX_Size() int {
	return xxx_messageInfo_PayloadObject.Size(m)
}
func (m *PayloadObject) XXX_DiscardUnknown() {
	xxx_messageInfo_PayloadObject.DiscardUnknown(m)
}

var xxx_messageInfo_PayloadObject proto.InternalMessageInfo

func (m *PayloadObject) GetSchema() string {
	if m != nil {
		return m.Schema
	}
	return ""
}

func (m *PayloadObject) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type SubscribeParams struct {
	Perspective *Perspective `protobuf:"bytes,1,opt,name=perspective,proto3" json:"perspective,omitempty"`
	Namespace   []byte       `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Uri         string       `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	// If specified, this proof will be used instead of building one for the
	// subscribe
	CustomProofDER []byte `protobuf:"bytes,4,opt,name=customProofDER,proto3" json:"customProofDER,omitempty"`
	// The unique identifier for the subscription. This enables you to resume
	// a previous subscription
	Identifier           string   `protobuf:"bytes,5,opt,name=identifier,proto3" json:"identifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeParams) Reset()         { *m = SubscribeParams{} }
func (m *SubscribeParams) String() string { return proto.CompactTextString(m) }
func (*SubscribeParams) ProtoMessage()    {}
func (*SubscribeParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_wavemq_4f4ebffe67269e9a, []int{7}
}
func (m *SubscribeParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeParams.Unmarshal(m, b)
}
func (m *SubscribeParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeParams.Marshal(b, m, deterministic)
}
func (dst *SubscribeParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeParams.Merge(dst, src)
}
func (m *SubscribeParams) XXX_Size() int {
	return xxx_messageInfo_SubscribeParams.Size(m)
}
func (m *SubscribeParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeParams.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeParams proto.InternalMessageInfo

func (m *SubscribeParams) GetPerspective() *Perspective {
	if m != nil {
		return m.Perspective
	}
	return nil
}

func (m *SubscribeParams) GetNamespace() []byte {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *SubscribeParams) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *SubscribeParams) GetCustomProofDER() []byte {
	if m != nil {
		return m.CustomProofDER
	}
	return nil
}

func (m *SubscribeParams) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

type SubscriptionMessage struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Message              *Message `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscriptionMessage) Reset()         { *m = SubscriptionMessage{} }
func (m *SubscriptionMessage) String() string { return proto.CompactTextString(m) }
func (*SubscriptionMessage) ProtoMessage()    {}
func (*SubscriptionMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_wavemq_4f4ebffe67269e9a, []int{8}
}
func (m *SubscriptionMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscriptionMessage.Unmarshal(m, b)
}
func (m *SubscriptionMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscriptionMessage.Marshal(b, m, deterministic)
}
func (dst *SubscriptionMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscriptionMessage.Merge(dst, src)
}
func (m *SubscriptionMessage) XXX_Size() int {
	return xxx_messageInfo_SubscriptionMessage.Size(m)
}
func (m *SubscriptionMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscriptionMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SubscriptionMessage proto.InternalMessageInfo

func (m *SubscriptionMessage) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *SubscriptionMessage) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*PeerSubscriptionTBS)(nil), "pb.PeerSubscriptionTBS")
	proto.RegisterType((*PeerSubscription)(nil), "pb.PeerSubscription")
	proto.RegisterType((*PublishParams)(nil), "pb.PublishParams")
	proto.RegisterType((*PublishResponse)(nil), "pb.PublishResponse")
	proto.RegisterType((*MessageTBS)(nil), "pb.MessageTBS")
	proto.RegisterType((*Message)(nil), "pb.Message")
	proto.RegisterType((*PayloadObject)(nil), "pb.PayloadObject")
	proto.RegisterType((*SubscribeParams)(nil), "pb.SubscribeParams")
	proto.RegisterType((*SubscriptionMessage)(nil), "pb.SubscriptionMessage")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WAVEMQClient is the client API for WAVEMQ service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WAVEMQClient interface {
	Publish(ctx context.Context, in *PublishParams, opts ...grpc.CallOption) (*PublishResponse, error)
	Subscribe(ctx context.Context, in *SubscribeParams, opts ...grpc.CallOption) (WAVEMQ_SubscribeClient, error)
}

type wAVEMQClient struct {
	cc *grpc.ClientConn
}

func NewWAVEMQClient(cc *grpc.ClientConn) WAVEMQClient {
	return &wAVEMQClient{cc}
}

func (c *wAVEMQClient) Publish(ctx context.Context, in *PublishParams, opts ...grpc.CallOption) (*PublishResponse, error) {
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, "/pb.WAVEMQ/Publish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wAVEMQClient) Subscribe(ctx context.Context, in *SubscribeParams, opts ...grpc.CallOption) (WAVEMQ_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_WAVEMQ_serviceDesc.Streams[0], "/pb.WAVEMQ/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &wAVEMQSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WAVEMQ_SubscribeClient interface {
	Recv() (*SubscriptionMessage, error)
	grpc.ClientStream
}

type wAVEMQSubscribeClient struct {
	grpc.ClientStream
}

func (x *wAVEMQSubscribeClient) Recv() (*SubscriptionMessage, error) {
	m := new(SubscriptionMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WAVEMQServer is the server API for WAVEMQ service.
type WAVEMQServer interface {
	Publish(context.Context, *PublishParams) (*PublishResponse, error)
	Subscribe(*SubscribeParams, WAVEMQ_SubscribeServer) error
}

func RegisterWAVEMQServer(s *grpc.Server, srv WAVEMQServer) {
	s.RegisterService(&_WAVEMQ_serviceDesc, srv)
}

func _WAVEMQ_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WAVEMQServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WAVEMQ/Publish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WAVEMQServer).Publish(ctx, req.(*PublishParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _WAVEMQ_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeParams)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WAVEMQServer).Subscribe(m, &wAVEMQSubscribeServer{stream})
}

type WAVEMQ_SubscribeServer interface {
	Send(*SubscriptionMessage) error
	grpc.ServerStream
}

type wAVEMQSubscribeServer struct {
	grpc.ServerStream
}

func (x *wAVEMQSubscribeServer) Send(m *SubscriptionMessage) error {
	return x.ServerStream.SendMsg(m)
}

var _WAVEMQ_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.WAVEMQ",
	HandlerType: (*WAVEMQServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _WAVEMQ_Publish_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _WAVEMQ_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "wavemq.proto",
}

func init() { proto.RegisterFile("wavemq.proto", fileDescriptor_wavemq_4f4ebffe67269e9a) }

var fileDescriptor_wavemq_4f4ebffe67269e9a = []byte{
	// 621 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x94, 0x4d, 0x6f, 0xd3, 0x4c,
	0x10, 0xc7, 0x65, 0x3b, 0x89, 0x9b, 0x49, 0x9a, 0xf6, 0xd9, 0x3c, 0xa2, 0x56, 0x84, 0xc0, 0xb2,
	0x04, 0x0a, 0x42, 0xaa, 0xda, 0x70, 0xe0, 0xc0, 0xa9, 0x88, 0x1c, 0x90, 0xa8, 0x08, 0x5b, 0x5e,
	0x4e, 0x1c, 0xd6, 0xce, 0xb6, 0x5d, 0x54, 0x7b, 0x97, 0xdd, 0x75, 0x4b, 0xbe, 0x01, 0x77, 0xbe,
	0x0e, 0x67, 0x3e, 0x17, 0xf2, 0xfa, 0x25, 0xeb, 0x10, 0x10, 0xbd, 0x70, 0xf3, 0xfc, 0x3d, 0xde,
	0x99, 0xf9, 0xf9, 0x3f, 0x0b, 0xc3, 0x1b, 0x72, 0x4d, 0xd3, 0xcf, 0x87, 0x42, 0x72, 0xcd, 0x91,
	0x2b, 0xe2, 0x09, 0x50, 0x22, 0x58, 0x19, 0x47, 0x2b, 0x18, 0x2f, 0x28, 0x95, 0x67, 0x79, 0xac,
	0x12, 0xc9, 0x84, 0x66, 0x3c, 0x7b, 0xfb, 0xfc, 0x0c, 0x45, 0x30, 0x54, 0x3c, 0x97, 0x09, 0x9d,
	0x67, 0x9a, 0xe9, 0x55, 0xe0, 0x84, 0xce, 0x74, 0x88, 0x5b, 0x1a, 0xba, 0x0b, 0xfd, 0x8c, 0xa4,
	0x54, 0x09, 0x92, 0xd0, 0xc0, 0x35, 0x09, 0x6b, 0x01, 0xed, 0x83, 0x97, 0x4b, 0x16, 0x78, 0xa1,
	0x33, 0xed, 0xe3, 0xe2, 0x11, 0x8d, 0xc0, 0x65, 0xcb, 0xa0, 0x63, 0x04, 0x97, 0x2d, 0xa3, 0x1b,
	0xd8, 0xdf, 0x2c, 0x8d, 0x1e, 0x81, 0xa7, 0x63, 0x65, 0xca, 0x0d, 0x66, 0x07, 0x87, 0x22, 0x3e,
	0xdc, 0xd2, 0x1d, 0x2e, 0x72, 0x8a, 0xf2, 0x8a, 0x5d, 0x64, 0x44, 0xe7, 0xb2, 0x29, 0xdf, 0x08,
	0x68, 0x02, 0x3b, 0x42, 0x72, 0x7e, 0xfe, 0x62, 0x8e, 0x4d, 0x0f, 0x43, 0xdc, 0xc4, 0xd1, 0x37,
	0x17, 0x76, 0x17, 0x79, 0x7c, 0xc5, 0xd4, 0xe5, 0x82, 0x48, 0x92, 0x2a, 0x74, 0x0c, 0x03, 0x41,
	0xa5, 0x12, 0x34, 0xd1, 0xec, 0x9a, 0x56, 0xe5, 0xf7, 0xca, 0xf2, 0x8d, 0x8c, 0xed, 0x9c, 0x5b,
	0x4f, 0xff, 0x18, 0xfc, 0x84, 0x67, 0x9a, 0x66, 0x3a, 0xe8, 0x84, 0xde, 0x74, 0x30, 0xfb, 0xcf,
	0x1c, 0x4f, 0x56, 0x57, 0x9c, 0x2c, 0x5f, 0xc7, 0x9f, 0x68, 0xa2, 0x71, 0x9d, 0x81, 0x8e, 0x60,
	0x4c, 0xb3, 0x44, 0xae, 0xcc, 0xc4, 0x0b, 0x22, 0x35, 0x2b, 0x1e, 0x82, 0x6e, 0xe8, 0x4d, 0x87,
	0x78, 0xdb, 0x2b, 0x14, 0x80, 0x5f, 0x74, 0xc7, 0x94, 0x0e, 0x7a, 0xa1, 0x33, 0xdd, 0xc1, 0x75,
	0x88, 0x1e, 0xc2, 0x28, 0xc9, 0x95, 0xe6, 0xe9, 0xa2, 0xe6, 0xe1, 0x9b, 0x6e, 0x37, 0xd4, 0x68,
	0x06, 0x7b, 0x15, 0x14, 0x4c, 0x95, 0xe0, 0x99, 0xa2, 0xe8, 0x3e, 0x74, 0xa9, 0x94, 0x5c, 0x56,
	0x40, 0xfa, 0x45, 0xc7, 0xf3, 0x42, 0xc0, 0xa5, 0x1e, 0xfd, 0x70, 0x00, 0x4e, 0xa9, 0x52, 0xe4,
	0x82, 0xfe, 0xad, 0x6b, 0x9e, 0xc2, 0xa8, 0x8c, 0x5f, 0xf1, 0x84, 0x98, 0xa9, 0xdc, 0x35, 0xed,
	0x5a, 0x7b, 0x87, 0x5f, 0xe2, 0x8d, 0xb4, 0x36, 0x70, 0xef, 0x37, 0xc0, 0x3b, 0x2d, 0xe0, 0xa2,
	0xa4, 0x6b, 0xb8, 0x6d, 0x07, 0x5e, 0x65, 0x44, 0x5f, 0x5d, 0xf0, 0xab, 0x41, 0x8a, 0xa9, 0x8d,
	0x55, 0xec, 0xa9, 0x0d, 0x25, 0x5c, 0xea, 0x2d, 0x6f, 0xb9, 0x6d, 0x6f, 0xa1, 0xb0, 0x34, 0xb0,
	0x67, 0x3e, 0x1d, 0x15, 0x9f, 0xae, 0xf9, 0x6c, 0xf1, 0x6d, 0x67, 0xd3, 0xb7, 0xb7, 0xff, 0xf3,
	0xf7, 0x00, 0x34, 0x4b, 0xa9, 0xd2, 0x24, 0x15, 0x2a, 0xe8, 0x85, 0xde, 0xd4, 0xc3, 0x96, 0x82,
	0xfe, 0x87, 0xee, 0x52, 0x72, 0xa1, 0x02, 0xdf, 0xbc, 0x2a, 0x03, 0xdb, 0x2f, 0x3b, 0x2d, 0xbf,
	0x44, 0x27, 0xb0, 0xdb, 0x82, 0x84, 0xee, 0x40, 0x4f, 0x25, 0x97, 0x34, 0x25, 0x06, 0x48, 0x1f,
	0x57, 0x51, 0x71, 0x44, 0xed, 0xe8, 0x92, 0x42, 0x1d, 0x46, 0xdf, 0x1d, 0xd8, 0xab, 0x76, 0x36,
	0xa6, 0xff, 0x6e, 0xc5, 0x7e, 0x75, 0x7a, 0x67, 0x9b, 0xd3, 0x0b, 0x62, 0x6c, 0x49, 0x33, 0xcd,
	0xce, 0x19, 0x95, 0x41, 0xd7, 0x1c, 0x60, 0x29, 0xd1, 0x47, 0x18, 0xdb, 0x37, 0x8e, 0xe5, 0x8b,
	0x3f, 0x6e, 0x03, 0x7a, 0x00, 0x7e, 0x5a, 0xe6, 0x56, 0x9e, 0x1e, 0x58, 0xff, 0x1f, 0xd7, 0xef,
	0x66, 0x5f, 0xa0, 0xf7, 0xe1, 0xe4, 0xfd, 0xfc, 0xf4, 0x0d, 0x3a, 0x06, 0xbf, 0x5a, 0x39, 0x54,
	0x9a, 0xd3, 0xbe, 0x94, 0x26, 0x63, 0x4b, 0x6a, 0x56, 0xf2, 0x19, 0xf4, 0x1b, 0xb2, 0xc8, 0x64,
	0x6c, 0x80, 0x9e, 0x1c, 0x58, 0xa2, 0xdd, 0xff, 0x91, 0x13, 0xf7, 0xcc, 0x9d, 0xff, 0xe4, 0x67,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xfa, 0x3f, 0xb5, 0x79, 0x13, 0x06, 0x00, 0x00,
}
